### ISSUE TITLE
Is there a way to parse the JSON to create the object?

### ISSUE THREAD

**Issue by juminoz** [danpaz/bodybuilder#113]
I would like to parse the JSON to create the object so that it can be modified further. Is there a way to do that with latest version of BodyBuilder?

**Comment by antonsamper** [comment]
You can do this after you have built the object. Do you have an example of what you want to achieve?

**Comment by juminoz** [comment]
Just any request created by the library itself.

For example:

```
var req = bodybuilder().filter('term', 'message', 'test').build();
var body = bodybuilder(req);
var modified = body.filter('term', 'title', 'some name').build();
```

**Comment by danpaz** [comment]
> parse the JSON to create the object

I'm guessing you're asking if it's possible to go "backwards" and create a bodybuilder instance from a built body. Kind of like `JSON.parse` on a json string. Right? If so that's not possible, although kind of a neat idea.

If you're looking for a way to continue modifying the query after calling `build`, one way to do that is to keep a reference to the "un-built" body. For example:

```js
var req = bodybuilder().filter('term', 'message', 'test');
var body = req.build(); // body is a snapshot of req
var modified = req.filter('term', 'title', 'some name').build();
```

**Comment by juminoz** [comment]
Thanks @danpaz. Yes, I need to be able to go "backwards" like JSON.parse. I'm dealing with saved searches like the case where the query is stored and reused when someone refreshes the page or sharing it with someone else (no long have reference to un-build JS object). Before using bodybuilder, I wrote my own library to do this, but now it seems like I will have to write something on top to put it back since this is not currently a feature. Will you potentially add this in the future?

**Comment by danpaz** [comment]
@juminoz Cool, thanks for explaining. I haven't thought about adding this in the future, and I don't yet know if something like this belongs in bodybuilder itself, in a separate library, a plugin, etc. Hard to tell without seeing the code and trying it out. I think the best approach is if you take a stab at writing something on top then report back here with what you found. Then we can decide whether a PR or a new project is the right next step.

**Comment by deleted** [comment]
@juminoz This might not be the answer you're looking for, but I've solved problems like this in the past with [serializr](https://github.com/mobxjs/serializr). It has a declarative syntax for defining a serialization format. Once defined, the library can do two way serialization & deserialization. You can create the serialization schema either in your application's model domain, or else potentially in the domain of Bodybuilder's unbuilt queries. Then you would store/share the serialized model, rather than a fully compiled ES query, and only build the query when you're ready to hit Elasticsearch.

To be a bit more concrete, a pattern I've used successfully before looks like this:
```
+-----------------+        +---------------+        +------------+
|  Serialized     |------->+ Application   +------> |BodyBuilder |
|  Representation |<-------+ Model Store   |        +------+-----+
+----+---+--------+        +---------------+               |
     |   ^                                                 v
     |   |                                        +--------+-------+
     v   |                                        |  ElasticSearch |
 +---+---+-----+                                  +----------------+
 | QueryString |
 +-------------+
```

You can imagine adding serialization/deserialization features to the BodyBuilder object itself without going through an intermediate Application Model representation, but to do it properly, you'd need the serialzer to support all the numerous features of BodyBuilder, which is a bit of a task.

**Comment by johannes-scharlach** [comment]
To a certain extent it should work to use `rawOption` – but no guarantee that clashes are going to be avoided. This would work well if you want to add aggregations to a query but not modify the query.
