### ISSUE TITLE
minimum_should_match?

### ISSUE THREAD

**Issue by mikeholmesuk** [danpaz/bodybuilder#114]
What's the correct way to be able to add a `minimum_should_match` option to a filtered `should`? I'm trying to end up with something like the following:

```
"filter": {
  "bool": {
    "should": [
      {
         "match": {
             "field_name": "foo"
          }
       },
       {
           "match": {
             "field_name": "bar"
            }
         },
         {
            "match": {
               "field_name": "baz"
            }
         }
     ],
      "minimum_should_match": "2<70%"
  }
}
...
```
I can get the `match` values in the filter using something like the following:
```
params[key].forEach(param => {
    builder.orFilter('match', 'field_name', param);
})
```
but no matter where I try and add `minimum_should_match` (as an option of each of the above `orFilter` calls, or as a separate `orFilter` call after the above) I get an invalid query. Seems that `bodybuilder` simply tries to add it as a new object in the filter. 

Any idea about how the above can be done?

**Comment by diegoprd** [comment]
i am experiencing the same problem... :(

**Comment by diegoprd** [comment]
Hi @mikeholmesuk , I found a work around for my case (I am working with orQueries instead of orFilters)... check if this also works for you:

So I am assigning a few orQueries
```
const body = bodybuilder()
  .orQuery('match','fieldName', {
      query: 'test',
      type: 'phrase_prefix'
    })
  .orQuery('match','anotherFieldname', {
      query: 'test',
      type: 'phrase_prefix'
    })
```
so after doing so I know the created body will have a `.query.bool` inside... so I am doing

```
body.getQuery().bool['minimum_should_match'] = 1
body.build()
```

and that is adding the `minimum_should_match` in the right place.

I just checked the code... and query-builder.js has the `getQuery` method
the filter-builder.js also have a `getFilter` method... so I guess you could use that.

hope it helps
best

**Comment by danpaz** [comment]
Thanks @diegoprd. I don't think there is a way to add a `minimum_should_match` option in the current api so that is the workaround I would suggest as well. I have a PR in the works.
