### ISSUE TITLE
Maintainers needed

### ISSUE THREAD

**Issue by ferronrsmith** [danpaz/bodybuilder#143]
Think it's time to seek maintainers. Taking too long to turn over issues.

**Comment by johannes-scharlach** [comment]
I'd be open to become a maintainer and help out more regularly.

Currently I see many issues being questions about how to use bodybuilder. These questions are often answered already and the issues could just be closed.

Quite a few issues are around missing & unclear documentation. I'd love to see more MRs that are improving this situation.

I'd love to value the work of all the people answering questions and improving documentations more by respecting the _all contributors_ spec: https://github.com/kentcdodds/all-contributors

**Comment by danpaz** [comment]
Hi! Thanks for opening this issue, this is a good discussion to start.

Agreed that it's taking too long to resolve issues. I am actually traveling this month without a computer so I'm unable to really review code properly. There's also a logistical issue in that Travis publishing to npm isn't currently working. So I've been blocked on the open issues/PRs lately and in the short term having another maintainer to push releases would be very helpful.

On the point of q&a issues: I've been really happy to see questions asked and answered by the community without my needing to get involved. I think this is really healthy! IMO sometimes maintainers should refrain from intervening to give other community members a chance to help each other. The all-contributors spec sounds great to me for giving these folks credit for their contributions.

Longer term: we need maintainers who make regular use of this tool. I made this lib a few years ago as a solution to a problem I was facing at work, and I'm thrilled others have made use of it too. Since then I've only been using it for a few simple use cases. I think bodybuilder should continue to be as small and simple as is necessary to get the job done, but bugfixes and new features are sometimes needed (clearly). Docs are a good example where a PR should just be merged and released asap. I could use help with this, though there are probably some logistical hoops we need to go through to give a maintainer enough permission to push and publish code.

@johannes-scharlach I can make you maintainer, especially to help out with the docs. @ferronrsmith are you interested in being a maintainer as well? As regular contributors you guys both seem well suited for it.

**Comment by ferronrsmith** [comment]
@danpaz yes I am interested.

**Comment by danpaz** [comment]
Added you both as collaborators on the project and @johannes-scharlach introduced #147 for all-contributors!
