### ISSUE TITLE
Prepend an aggregation to an existing aggregation

### ISSUE THREAD

**Issue by shaharmor** [danpaz/bodybuilder#145]
Hi,

I need to be able to add an aggregation as the top level aggregation of existing aggregations.

So this:

```json
{
  "aggs": {
    "agg_terms_browser": {
      "terms": {
        "field": "browser"
      }
    }
  }
}
```

will be updated to this:

```json
{
  "aggs": {
    "agg_terms_os": {
      "terms": {
        "field": "os"
      },
      "aggs": {
        "agg_terms_browser": {
          "terms": {
            "field": "browser"
          }
        }
      }
    }
  }
}
```

**Comment by ferronrsmith** [comment]
You can use nest aggregations, e.g.

```javascript
bodybuilder().aggregation('terms', 'os', null, agg => agg.aggregation('terms', 'browser')).build()
````

```json
{
  "aggs": {
    "agg_terms_os": {
      "terms": {
        "field": "os"
      },
      "aggs": {
        "agg_terms_browser": {
          "terms": {
            "field": "browser"
          }
        }
      }
    }
  }
}
```

**Comment by shaharmor** [comment]
@ferronrsmith this is in the case where I know about all the aggregations in advance, but if I don't I want to be able to modify existing aggregations using the same API

**Comment by johannes-scharlach** [comment]
You can also bring your own bodybuilder for the nested aggregation:

```js
const mainBuilder = bodybuilder()
const nestedAggregationBuilder = bodybuilder()

// …
nestedAggregationBuilder.aggregation('terms', 'browser')

// …
const body = mainBuilder.aggregation('terms', 'os', null, () => nestedAggregationBuilder).build()
```

There are other options too, like creating the callback-function for the nested aggregation earlier

```js
const aggregationCallback = (nestedAggregationBuilder) => {
  return nestedAggregationBuilder.aggregation('terms', 'browser')
}

// …
const body = bodybuilder().aggregation('terms', 'os', null, aggregationCallback).build()
```

I'd generally advise to use the second approach, since the first one might potentially be removed in the future (there are currently no plans to do so though).

You'll always need to know all sub-aggregations by the time you add the `agg_terms_os` aggregation, otherwise it's not possible to identify to which aggregation you'd like to add a subaggregation.

Does this help?

**Comment by johannes-scharlach** [comment]
Closing this for now. We'll reopen if there still is an issue.
