### ISSUE TITLE
better support for basic multi_match in query

### ISSUE THREAD

**Issue by punit-kulal** [danpaz/bodybuilder#242]
This may seem a duplicate of #129, but keeping in the line with predictability of the api.
shouldn't 
```js
.query('multi_match', ['field1','field2'], 'queryTerm') 
```
automatically translate to 
```js
{"multi_match" : {
      "query":    "queryTerm", 
      "fields": [ "field1", "field2" ]
    }
}
```
This seems extremely intuitive.
I could submit a pull request for the same

**Comment by ferronrsmith** [comment]
Seems like v1. The whole issue predictability is limitations and this, while it might be easier to read and digest, might limiting.


```javascript
bodybuilder()
    .query(
        'multi_match',
        {
            query: 'queryTerm',
            [ "field1", "field2" ]
        }
    )
    .build();
```

Seems very intuitive to me.

Problem with your suggestion is.. What happens when u need to add more options ?

```javascript
bodybuilder()
    .query(
        'multi_match',
        {
            query: 'hello',
            fuzziness: 5,
            prefix_length: 0,
            fields: ['Field1^1000', 'Field2^3', 'Field3^2', 'Field4']
        }
    )
    .build();
```

how'd u handle this ? The API is designed in a way that allows it to be as dsl-agnostic  as possible. We don't want to be fine-tuning and changing the APIs every time ES makes an upstream change/addition.

i.e bodybuilder wasn't designed to fit all use-cases. Sometimes you need a hammer, n other times you need sledge.

Feel free to submit your PR, we'll have a look. If it doesn't break the current flow it'll be considered.
