### ISSUE TITLE
Please add support of suggestions

### ISSUE THREAD

**Issue by georgyfarniev** [danpaz/bodybuilder#263]
Hi. Thanks for working on bodybuilder, it is very useful module. Can you please add support of suggestions feature for consistency? Thanks.

**Comment by danpaz** [comment]
I don't have the bandwidth to work on new features like this at the moment, unfortunately. If you are willing to contribute a PR I would be happy to review it.

**Comment by georgyfarniev** [comment]
@danpaz thanks for reply. I’ll try to make it when I have time and PR. Glad that you approve this idea, because I saw your comment which made me confused about it.

**Comment by danpaz** [comment]
@georgyfarniev how much of the [Suggesters API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html) are you looking to support? Simple usage of `suggest` clauses could make sense to include in this library since they are meant to complement query results. The structure is even similar to queries for simple cases. 

But I am concerned that supporting the entire Suggesters API could add a lot of surface area to this simple library. I would suggest trying to follow the pattern of `query-builder`, `filter-builder` and `aggregation-builder` which all make use of the same [`buildClause`](https://github.com/danpaz/bodybuilder/blob/3a51103959870b2c8e83395f6d489bba0ee6f1af/src/utils.js#L48) utility to construct query clause objects. Let me know how that goes and we can evaluate if bodybuilder is still the best place for this functionality.

**Comment by georgyfarniev** [comment]
@danpaz thanks for pointing me out. I'll work on it and let you know, but I also bit overwhelmed now due to current situation in my life. Hope to get it done soon.

**Comment by quinnlangille** [comment]
@georgyfarniev @danpaz I have some available bandwidth to put this together, I'll work on a draft PR over the next week!
