### ISSUE TITLE
Embed types into the source code

### ISSUE THREAD

**Issue by johnnyraphic** [danpaz/bodybuilder#312]
Embed types into the source code and not only into the `bodybuilder.d.ts` file which would be easier to maintane with further changes to the API.

Currently im trying to use es6 imports and using the bodybuilder object and it seems to be a lot more trouble than it needs to be in a typescript project imo.

I would like to start working on migrating to ts this weekend but would first want to know if it is even desierd and secoundly if there are any prerequists to start working on this issue.

I would like to add better support to ts in this project since I was about to consider not using it in the project im working on atm but this project is a great idea and for me the TS support is a bit lacking for my use.

Thanks in advance, John :)

**Comment by johannes-scharlach** [comment]
@johnnyraphic Take a look at https://github.com/johannes-scharlach/elasticbuilder

2 years ago I did an almost complete re-write of bodybuilder in TS while copying most of the tests from this project. And since bodybuilder hasn't really changed since then this should still be up to date.

You can think of that project as a major update to bodybuilder with a breaking API change (and without any testing in production so far).
What's missing to merge it back into this project is backwards compatibility to the (very versatile) bodybuilder API. I believe that that's actually possible, so if you want to make bodybuilder work with TS, that's probably the easiest path.
