### ISSUE TITLE
The new logo has arrived.

### ISSUE THREAD

**Issue by PythonProdigy** [danpaz/bodybuilder#4]
It's raining here, quite profusely. I just finished watching the Battle of Chemulpo Bay. It's a silent film that was developed in 1904. Much like the current bodybuilder logo, I felt that it lacked expression. It looks like the current logo is just an enlarged JPEG of the flex emoji. So I immediately thought, we can do better than that!

Two years ago I purchased a book from Amazon titled [The Book of GIMP: A Complete Guide to Nearly Everything](http://www.amazon.com/Book-GIMP-Complete-Nearly-Everything/dp/1593273835/). Much to my dismay, it does a very poor job at covering nearly everything. I dusted it off and read a couple chapters with my morning tea (I only drink decaffeinated Japanese-style sencha tea now since my ordeal, but that's a story for another issue).

I decided to flex my GIMP skills a bit and produce a new logo for the project. There's still room for improvement, but it's original and pretty damn classy if I do say so myself. 

Juliette Aristides once said, "Often the most unique, compelling work comes not from a concept or an idea but from a deep, wordless place inside the artist."

I believe that when you look into this logo you will find a little piece of me inside.

![bodybuilder](https://cloud.githubusercontent.com/assets/16299511/11818468/1f4d5c5a-a320-11e5-9558-a7e4f847e486.jpeg)

**Comment by ahaurw01** [comment]
:+1:

**Comment by d6u** [comment]
:joy:

**Comment by d6u** [comment]
The logo is awesome. Seriously though, you should get rid of the smoky background.

**Comment by ahaurw01** [comment]
I was thinking more smoke. I like this a lot.

**Comment by FlaMango** [comment]
Yes I think more smoke would be good,, and can You make a logo for my forum? PM me

**Comment by PythonProdigy** [comment]
Thank you all for the positive criticisms and words of encouragement. I decided to revise the logo a bit at the recommendation of @ahaurw01 . I added more smoke so it looks like the logo is slowly emerging from the fog, and some wind effects to look like the body builder is fast and more masculine.

I believe I'm correct in making the assumption that men are the primary users of this product. Men are  very particular and tend to tightly target their perception; their notion of cause and effect is linear and because of this men are visually-oriented. What they see is what is, literally. Seeking clarity, men create absolute distinctions. Is the man muscular? Does he look good? Do I want to be like this man? Is the logo clear, concise and easy to digest?

![untitled-1](https://cloud.githubusercontent.com/assets/16299511/11821396/dc8b88ce-a32e-11e5-801f-25120f591627.jpg)

**Comment by danpaz** [comment]
@PythonProdigy I'm really impressed and touched that you took the time to make a logo for this project. I have to say though that I quite like the current existing logo. I like that it's an emoji, because it's universally recognized, and I can insert it almost anywhere: [tweets](https://twitter.com/danpazsoldan/status/676524642643910656), [repo descriptions](https://github.com/danpaz/bodybuilder), commit messages, comments :muscle:, etc. Plus I feel that a logo like the one you created sets the tone that the project is serious, mysterious, and well-defined (ha! puns.). At this early stage I'd like to not take branding too seriously, but happy to revisit logos when the project has matured a bit. Thanks for jumping in and getting involved!
