### ISSUE TITLE
Help with deferred aggregation addition

### ISSUE THREAD

**Issue by davecranwell** [danpaz/bodybuilder#46]
I've got a problem I'm hoping you can help with. See: http://jsbin.com/bagarujomo/edit?html,js,output

Essentially I have two arrays of items which are _not_ known at runtime (unlike this contrived example) and I want items in the second array to be added as sub-aggregates of particular items in the first array. 

My JS around apply(), call(), partials, currying etc is rather shakey and I'm sure they're the solution here, but I was hoping you might know a quick answer to this having no doubt addressed this yourself.

**Comment by danpaz** [comment]
@davecranwell I'm not sure this is currently possible because [this code](https://github.com/danpaz/bodybuilder/blob/master/src/aggregations/aggregation-builder.js#L39) evaluates the nested aggregation immediately, and looks for the `_aggs` property to set on the builder. But I haven't taken too close of a look so maybe @nfantone (the original author of nested aggregations) has more thoughts on this?

**Comment by nfantone** [comment]
> Essentially I have two arrays of items which are not known at runtime

@davecranwell Surely you meant they are not known at "compile time" (if you could say that about JS, that is). Otherwise, _when_ do they become known?

Currently, as @danpaz correctly mentioned, aggs are evaluated during build and you can't "edit" them after their addition. So, what's wrong with creating a whole `BodyBuilder` instance when you _do_ know how to build your query? I'm not sure I understood your case fully, though.

For starters, in your bin example, the nesting function [should return the nested object](https://github.com/danpaz/bodybuilder#nested-aggregations) but yours does not.

**Comment by danpaz** [comment]
Closing for now as we haven't heard back in a while.
