### ISSUE TITLE
Migration guide for bodybuilder 2

### ISSUE THREAD

**Issue by danpaz** [danpaz/bodybuilder#79]
Write a guide for existing users of bodybuilder to migrate their code to the new version. Include at least:
- [x] Reasons to update to the new version, or not to update.
- [x] List of breaking changes.
- [x] Code samples comparing the old code and the new code.

**Comment by johannes-scharlach** [comment]
I was wondering if it makes sense to still support the v1 syntax in bodybuilder v2? The End of Life for Elasticsearch 1.x is in January https://www.elastic.co/support/eol (commenting here, since this would be a breaking change)

Another option would be to just switch the defaults to make v2 the default.

I'd just like to keep it as simple as possible and think removing the v1 support might help. What are your thoughts?

**Comment by danpaz** [comment]
Thats a fair point. I think it's still worth supporting the v1 syntax in bodybuilder 2, even though it will be EOL'd soon I suspect many will still take more time to upgrade (including my company :)). But I like the idea of switching the default to v2 and noting this in the migration doc.
